---
- name: SageMaker HyperPod Slurm Lifecycle Configuration
  hosts: localhost
  become: yes
  gather_facts: yes
  vars_files: 
    - ../vars/main.yml

  pre_tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes
      changed_when: false
  
  roles:
    - role: common
    - role: install_packages
  
  post_tasks:
    - name: Success message
      debug:
        msg: "[INFO]: Success: All provisioning scripts completed"
