---
- name: Install common dependencies
  apt: 
    name: 
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - squashfs-tools
      - parallel
      - fuse-overlayfs
      - squashfuse
    state: present

- name: Include Ansible installation task
  include_tasks: ansible.yml
